theme: jekyll-theme-cayman
title: Learning to Segment from Scribbles using<br>Multi-scale Adversarial Attention Gates
description: Gabriele Valvano, Andrea Leo, Sotirios A. Tsaftaris
google_analytics: UA-169250566-1
show_downloads: true
button_home_url: index
button_paper_url: https://arxiv.org/abs/2007.01152
button_code_url: https://github.com/gvalvano/multiscale-adversarial-attention-gates
button_data_url: data
button_contacts_url: contacts
banner: https://github.com/vios-s/multiscale-adversarial-attention-gates/blob/main/images/banner.pdf
plugins:
  - jemoji
image_url_prefix: images
